### ISSUE TITLE
Add support for IPv4 and IPv6 lookup

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [kissgyorgy/whatsmyip-go#1]
Currently, if available, only the IPv6 address is returned. A flag specifying the requested IP version would be helpful.

**Comment by kissgyorgy** [comment]
Will do! Thanks for the suggestion, I just noticed it today myself.

**Comment by kissgyorgy** [comment]
Hey! I made a new release, check it out and let me know if it works for you!
